name: biobb_wf_flexserv
channels:
  - conda-forge
  - bioconda
dependencies:
  - biobb_flexserv==4.1.0
  - biobb_io==4.1.1
  - biobb_structure_utils==4.1.0
  - biobb_analysis==4.1.0
  - jupyter
  - plotly
  - nglview==3.0.8
  - ipywidgets=7.7.2
  - simpletraj
