name: biobb_wf_flexserv
channels:
  - conda-forge
  - bioconda
dependencies:
  - python==3.8
  - biobb_flexserv==4.1.0
  - biobb_io==4.1.0
  - biobb_structure_utils==4.1.0
  - biobb_analysis==4.1.0
  - ipywidgets==7.6.6
  - jupyter_client==7.3.2
  - importlib_metadata
  - plotly
  - nglview
  - simpletraj